name: CI

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
        python-version:
          - "2.x"
          - "3.x"

    steps:
      - uses: actions/checkout@v2.2.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set Python version variables
        run: printf '::set-env name=PYTHON_VERSION::%s\n' "$(/usr/bin/env python -c 'import sys; print(sys.version_info.major)')"

      - name: Install dependencies
        run: |
          PLATFORM=$(uname)
          if [ "${PLATFORM}" = "Linux" ]; then
            sudo apt-get install -y zsh
          fi

      - name: Create calibre directories
        run: |
          CALIBRE_DIR="$(mktemp -d XXXXXXXXX)"
          CALIBRE_CONFIG_DIRECTORY="${CALIBRE_DIR}/config"
          CALIBRE_TEMP_DIR="${CALIBRE_DIR}/tmp"
          mkdir -p "${CALIBRE_CONFIG_DIRECTORY}" "${CALIBRE_TEMP_DIR}"
          printf '::set-env name=CALIBRE_DIR::%s\n' "${CALIBRE_DIR}"
          printf '::set-env name=CALIBRE_CONFIG_DIRECTORY::%s\n' "${CALIBRE_CONFIG_DIRECTORY}"
          printf '::set-env name=CALIBRE_TEMP_DIR::%s\n' "${CALIBRE_TEMP_DIR}"

      - name: Build plugin ZIP files
        run: ./scripts/build.sh build

      - name: Install Python test dependencies
        run: |
          set -x
          python2 -m pip install --upgrade pip
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi
          if [ -f scripts/requirements.txt ]; then
            python -m pip install -r scripts/requirements.txt
          fi
          if [ -f tests/requirements.txt ]; then
            python -m pip install -r tests/requirements.txt
          fi
          if [ "${PYTHON_VERSION}" != "3" ]; then
            if [ -f requirements.txt ]; then
              python3 -m pip install -r requirements.txt
            fi
            if [ -f scripts/requirements.txt ]; then
              python3 -m pip install -r scripts/requirements.txt
            fi
            if [ -f tests/requirements.txt ]; then
              python3 -m pip install -r tests/requirements.txt
            fi
          fi
          python3 -V

      - name: Fetch calibre for Python ${{ matrix.python-version }}
        run: python3 ./scripts/update-calibre.py $PYTHON_VERSION

      - name: Run calibre Python ${{ matrix.python-version }} tests
        run: ./scripts/build.sh test $PYTHON_VERSION
