name: CI

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
        python-version:
          - "2.x"
          - "3.x"

    steps:
      - uses: actions/checkout@v2.2.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python test dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi;
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi;
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi;

      - name: Fetch calibre for Python ${{ matrix.python-version }}
        run: ./scripts/update-calibre.py ${{ matrix.python-version }}

      - name: Set Python version
        run: printf '::set-env name=PYTHON_VERSION::%s\n' "$(/usr/bin/env python -c 'import sys; print(sys.version_info.major)')"

      - name: Run calibre Python ${{ matrix.python-version }} tests
        run: make test_py$PYTHON_VERSION
