---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI

# Controls when the action will run. Workflow runs when manually triggered
# using the UI or API.
'on':
  push:
    branches:
      - '*'
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'macos-latest'
          - 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2.2.0

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          PLATFORM=$(uname)
          if [ "${PLATFORM}" = "Linux" ]; then
            sudo apt-get install -y zsh
          fi

      # yamllint disable rule:line-length
      - name: Create calibre directories
        run: |
          CALIBRE_DIR="$(mktemp -d XXXXXXXXX)"
          CALIBRE_CONFIG_DIRECTORY="${CALIBRE_DIR}/config"
          CALIBRE_TEMP_DIR="${CALIBRE_DIR}/tmp"
          mkdir -p "${CALIBRE_CONFIG_DIRECTORY}" "${CALIBRE_TEMP_DIR}"
          printf '::set-env name=CALIBRE_DIR::%s\n' "${CALIBRE_DIR}"
          printf '::set-env name=CALIBRE_CONFIG_DIRECTORY::%s\n' "${CALIBRE_CONFIG_DIRECTORY}"
          printf '::set-env name=CALIBRE_TEMP_DIR::%s\n' "${CALIBRE_TEMP_DIR}"
      # yamllint enable rule:line-length

      - name: Install calibre from upstream
        run: ./scripts/update-calibre.py

      - name: Build plugin ZIP files
        run: ./scripts/build.sh

      - name: Install Python test dependencies
        run: |
          set -x
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          fi
          if [ -f scripts/requirements.txt ]; then
            python3 -m pip install -r scripts/requirements.txt
          fi
          if [ -f tests/requirements.txt ]; then
            python3 -m pip install -r tests/requirements.txt
          fi

      - name: Run calibre Python ${{ matrix.python-version }} tests
        run: ./scripts/build.sh test
