---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Lint

'on':
  push:
    branches:
      - '*'
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: psf/black@main

  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: jgoguen/gh-actions/shellcheck@main

  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: yamllint
        uses: jgoguen/gh-actions/yaml-lint@main
        with:
          source: ./.github/workflows/

  vale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: File Changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Lint Markdown files
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '${{ steps.file_changes.outputs.files_modified }}'
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/proselint/releases/latest/download/proselint.zip
            https://github.com/errata-ai/Joblint/releases/latest/download/Joblint.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
