---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Lint

'on':
  push:
    branches:
      - '*'
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - uses: psf/black@master

  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0

      - uses: jgoguen/gh-actions/shellcheck@main

  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0

      - name: yamllint
        uses: nosborn/github-action-yamllint@v1
        with:
          files_or_dir: ./.github/workflows/
