---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Populate Release

'on':
  push:
    tags:
      - 'v*'

jobs:
  upload-assets:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Install repo dependencies
        run: sudo apt install -y gettext

      - name: Check out release tag
        uses: actions/checkout@v2.2.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Fetch calibre
        run: ./scripts/update-calibre.py 3

      - name: Build ZIP files
        run: ./scripts/build.sh build

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: softprops/action-gh-release
        with:
          files: '*.zip'
