---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Populate Release

'on':
  push:
    tags:
      - 'v*'

jobs:
  upload-assets:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2.2.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Fetch calibre
        run: ./scripts/update-calibre.py 3

      - name: Build ZIP files
        run: ./scripts/build.sh build

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload KoboTouchExtended
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./KoboTouchExtended.zip
          asset_name: KoboTouchExtended.zip
          asset_content_type: application/zip

      - name: Upload KePub Input
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./KePub Input.zip
          asset_name: KePub Input.zip
          asset_content_type: application/zip

      - name: Upload KePub Output
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./KePub Output.zip
          asset_name: KePub Output.zip
          asset_content_type: application/zip

      - name: Upload KePub Metadata Reader
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./KePub Metadata Reader.zip
          asset_name: KePub Metadata Reader.zip
          asset_content_type: application/zip

      - name: Upload KePub Metadata Writer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./KePub Metadata Writer.zip
          asset_name: KePub Metadata Writer.zip
          asset_content_type: application/zip
